# -*- coding: utf-8 -*-
import sys
from PyQt4 import QtGui
sys.path.append('../Controladores')
from Main_Controller import *


class MainWindow(QtGui.QWidget):

    def __init__(self):
        super(MainWindow, self).__init__()
        self.controlador = MainController(self)
        self.init_ui()

    def init_ui(self):
        self.display = QtGui.QLineEdit()
        h_layout = QtGui.QHBoxLayout()

#Botones C
        igual = QtGui.QPushButton('=')
        menos = QtGui.QPushButton('-')
        mas = QtGui.QPushButton('+')
        negativo = QtGui.QPushButton('(-)')
        uno = QtGui.QPushButton('1')
        dos = QtGui.QPushButton('2')
        tres = QtGui.QPushButton('3')
        cuatro = QtGui.QPushButton('4')
        cinco = QtGui.QPushButton('5')
        seis = QtGui.QPushButton('6')
        siete = QtGui.QPushButton('7')
        ocho = QtGui.QPushButton('8')
        nueve = QtGui.QPushButton('9')
        cero = QtGui.QPushButton('0')
        derecha = QtGui.QPushButton('→')
        izquierda = QtGui.QPushButton('←')
        punto = QtGui.QPushButton('.')
        coma = QtGui.QPushButton(',')
        clear = QtGui.QPushButton('<')
        clearAll = QtGui.QPushButton('<<')

#Funciones C
        h_layout.addWidget(igual)
        h_layout.addWidget(menos)
        h_layout.addWidget(mas)
        h_layout.addWidget(uno)
        h_layout.addWidget(dos)
        h_layout.addWidget(tres)
        h_layout.addWidget(cuatro)
        h_layout.addWidget(punto)
        h_layout.addWidget(self.display)

#Botones C Cientifica
        sen = QtGui.QPushButton('sin')
        cos = QtGui.QPushButton('cos')
        tan = QtGui.QPushButton('tan')
        log = QtGui.QPushButton('log()')
        raiz = QtGui.QPushButton('√')
        ans = QtGui.QPushButton('Ans')
        porcentaje = QtGui.QPushButton('%')
        exponenteDiez = QtGui.QPushButton('x10ª')
        parentesisIzquierdo = QtGui.QPushButton('(')
        parentesisDerecho = QtGui.QPushButton(')')
        cuadrado = QtGui.QPushButton('x²')
        potencia = QtGui.QPushButton('xª')
        factorial = QtGui.QPushButton('factorial()')
        yen = QtGui.QPushButton('¥')
        libra = QtGui.QPushButton('£')
        euro = QtGui.QPushButton('€')
        peso = QtGui.QPushButton('$a')
        dolar = QtGui.QPushButton('$')
        bitCoin = QtGui.QPushButton('฿')

#funcion Cientifica
        h_layout.addWidget(parentesisIzquierdo)
        h_layout.addWidget(parentesisDerecho)

#ConexionDeBotones
        derecha.clicked.connect(self.controlador.handler_derecha)
        izquierda.clicked.connect(self.controlador.handler_izquierda)
        igual.clicked.connect(self.controlador.operation)
        menos.clicked.connect(self.controlador.handler_write)
        mas.clicked.connect(self.controlador.handler_write)
        negativo.clicked.connect(self.controlador.handler_write)
        uno.clicked.connect(self.controlador.handler_write)
        dos.clicked.connect(self.controlador.handler_write)
        tres.clicked.connect(self.controlador.handler_write)
        cuatro.clicked.connect(self.controlador.handler_write)
        cinco.clicked.connect(self.controlador.handler_write)
        seis.clicked.connect(self.controlador.handler_write)
        siete.clicked.connect(self.controlador.handler_write)
        ocho.clicked.connect(self.controlador.handler_write)
        nueve.clicked.connect(self.controlador.handler_write)
        cero.clicked.connect(self.controlador.handler_write)
        raiz.clicked.connect(self.controlador.handler_write)
        ans.clicked.connect(self.controlador.handler_write)
        porcentaje.clicked.connect(self.controlador.handler_write)
        exponenteDiez.clicked.connect(self.controlador.handler_write)
        parentesisIzquierdo.clicked.connect(self.controlador.handler_write)
        parentesisDerecho.clicked.connect(self.controlador.handler_write)
        cuadrado.clicked.connect(self.controlador.handler_write)
        potencia.clicked.connect(self.controlador.handler_write)
        factorial.clicked.connect(self.controlador.handler_write)
        yen.clicked.connect(self.controlador.handler_write)
        libra.clicked.connect(self.controlador.handler_write)
        euro.clicked.connect(self.controlador.handler_write)
        peso.clicked.connect(self.controlador.handler_write)
        dolar.clicked.connect(self.controlador.handler_write)
        bitCoin.clicked.connect(self.controlador.handler_write)
        clear.clicked.connect(self.controlador.handler_write)
        clearAll.clicked.connect(self.controlador.handler_write)
        coma.clicked.connect(self.controlador.handler_write)
        sen.clicked.connect(self.controlador.handler_write)
        cos.clicked.connect(self.controlador.handler_write)
        tan.clicked.connect(self.controlador.handler_write)
        log.clicked.connect(self.controlador.handler_write)
        punto.clicked.connect(self.controlador.handler_write)

        self.setLayout(h_layout)
        self.setWindowTitle('Calculadora')
        self.setGeometry(200, 200, 200, 200)
        self.show()

app = QtGui.QApplication(sys.argv)
window = MainWindow()
sys.exit(app.exec_())